from application import db

User_Goal = db.Table("user_goal",
    db.Column(  'id',
                db.Integer,
                primary_key = True),
    db.Column(  'user_id',
                db.Integer,
                db.ForeignKey('user.id')),
    db.Column(  'persona_id',
                db.Integer,
                db.ForeignKey('persona.id')),
    db.Column(  'goal_id',
                db.Integer,
                db.ForeignKey('goal.id')),
    db.Column(  'scoring_system_id',
                db.Integer,
                db.ForeignKey('scoring_system.id')),
    db.Column(  'schedule_id',
                db.Integer,
                db.ForeignKey('reminder_schedule.id')))