from application import db

User_Habit = db.Table("user_habit",
    db.Column(  'id',
                db.Integer,
                primary_key = True),
    db.Column(  'user_id',
                db.Integer,
                db.ForeignKey('user.id')),
    db.Column(  'persona_id',
                db.Integer,
                db.ForeignKey('persona.id')),
    db.Column(  'habit_id',
                db.Integer,
                db.ForeignKey('habit.id')),
    db.Column(  'scoring_system_id',
                db.Integer,
                db.ForeignKey('scoring_system.id')),
    db.Column(  'schedule_id',
                db.Integer,
                db.ForeignKey('reminder_schedule.id')))